spring:
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    host: localhost
    #    host: 127.0.0.1
    port: 6379
    password:
    #    cluster:
    #      nodes:
    #      - 127.0.0.1:6379
    #      - 127.0.0.1:6380
    #      - 127.0.0.1:6381
    #      - 127.0.0.1:6382
    #    jedis: