
server:
  port: 9100
#hosts 文件 127.0.0.1 zuul28080.com
nacos:
  gateway:
    route:
      config:
        data-id: gateway-router
        group: DEFAULT_GROUP

spring:
  application:
    name: gateway
  profiles:
    #local,sit,uat,prod
    active: sit
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: f4fde7b5-29f4-4f59-a8c9-b363c6034f47
      config:
        server-addr: 127.0.0.1:8848
        namespace: f4fde7b5-29f4-4f59-a8c9-b363c6034f47
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#      routes: #当访问http://localhost:28080/demo,直接转发到http://localhost:9100/demo
#      - id: user-service
#        uri: lb://restful-consumer/user
#        predicates:
#        - Path=/rest/user/**
#        filters:
#        - StripPrefix=1
#      routes: #当访问http://localhost:28080/demo,直接转发到http://localhost:9100/demo
#      - id: user-service
#        uri: lb://restful-consumer/user
#        predicates:
#        - Path=/rest/user/**
#        filters:
#        - StripPrefix=1
#      - id: swagger
#        uri: http://localhost:9104/v2/
#        predicates:
#        - Path=/v2/api-docs

#  redis:
#    lettuce:
#      pool:
#        # 连接池中的最大空闲连接 默认8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认0
#        min-idle: 0
#        # 连接池最大连接数 默认8 ，负数表示没有限制
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
#        max-wait: -1



info:
  app.name: jchj-gateway
  company.name: com.jchj
  build.artifactId: $project.artifactId$
  build.version: $project.version$


logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.ipc.netty: INFO

