app:
  id: jchj
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: ENC(NrkSmz/3s1cgdNvTFfU7mOQwtEFjodV9ysO/bpB6imbFYH6nShpDExWnzNCKGVpLcES+wZ6e8TEArq83EP8LC592VutW87lyISBa74V4QliuGH9kr/fGiGg00ELPqkc6BsbDVblKc9ZRiUnpu4HWQoHYsrngwFy3TkdjI2t0FEQ=)
#    username: ENC(LZmkNjmRG/4oce1AxSgvmofOPcyutyiB59hItqjdwTQPnMpQvns1zQ3PzX1xD8W3)
#    password: ENC(cJ7sH0s5t1x/uHxDoZyVotVrSOXr9iWrkKv4Nqgeo0vsQ1aa3H3Xzs5G/PhnKeYu)
#    # using Hikari
#    hikari:
#      autoCommit : true
#      connectionTestQuery : "select 'x'"
#      connectionTimeout : 30000
#      idleTimeout : 600000
#      initializationFailTimeout : 1
#      maxLifetime : 1800000
#      maximumPoolSize : 10
#      minimumIdle : 1
#      validationTimeout : 5000
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
#        useLocalSessionState: true
#        rewriteBatchedStatements: true
#        cacheResultSetMetadata: true
#        cacheServerConfiguration: true
#        elideSetAutoCommits: true
#        maintainTimeStats: false
